### ISSUE TITLE
Sheep don't regrow coats. 

### ISSUE THREAD

**Issue by KohlrabitoDev** [froobynooby/FarmControl#46]
Exactly as title says, sheep wont regrow their coats if you don't disable them in the config.

**Comment by KohlrabitoDev** [comment]
Not entirely sure, reporting this as someone who downloaded, dragged & dropped the plugin into my servers plugins folder, & restarted my server. It works fine for everything else, but if I had to assume it’s probably remove-ai, because the sheep aren’t even trying to eat grass

**Comment by froobynooby** [comment]
If you've not changed any settings then the sheep should only be affected by the `disable-collisions` and `remove-random-movement` actions, which I've just tested locally and confirmed do not affect wool regrowth. Check your config to see if you've enabled any profiles that use `remove-ai` or `remove-awareness` and also check in-game with `/farmcontrol status` to see if any entities are affected by those actions. Otherwise, I don't think it's a FarmControl causing it
